#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6034-webs
    bind *:80
    mode http
    balance roundrobin
    server 5974-web-01 184.72.77.230:80 check
    server 5974-web-02 107.23.161.253:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart    
